name: hello world

on:
  pull_request:
    branches: [ "main" ]
  push:
    branches: [ "main" ]
jobs:
  hello_world:
    runs-on: ubuntu-latest
    steps:
      - run: echo "hello world"
  build:
    runs-on: ubuntu-latest
    steps:
      - run: echo "hello world"
  test:
    runs-on: ubuntu-latest
    steps:
      - run: echo "hello world"
  publish:
    runs-on: ubuntu-latest
    steps:
      - run: echo "hello world"
    
